/* eslint-disable prettier/prettier */
/**
 * @deprecated This Invoice model class is deprecated.
 * Use CreateInvoiceDto for API requests and InvoiceEntity as the single source of truth.
 * This class is kept for backward compatibility but should not be used in new code.
 * 
 * Migration path:
 * - For API requests: Use CreateInvoiceDto
 * - For database operations: Use InvoiceEntity
 * - This class will be removed in a future version
 */
import { BillsEntity } from 'src/finance/entities/bills.entity';
import { StudentsEntity } from 'src/profiles/entities/students.entity';
import { BalancesEntity } from 'src/finance/entities/balances.entity';
import { EnrolEntity } from 'src/enrolment/entities/enrol.entity';

 
/** @deprecated Use CreateInvoiceDto and InvoiceEntity instead */
export class Invoice {
  constructor(
    public totalBill: number,

    public balanceBfwd: BalancesEntity,
    public student: StudentsEntity,
    public bills: BillsEntity[],

    public balance: number,
    public enrol?: EnrolEntity,
    public invoiceNumber?: string,

    public invoiceDate: Date = new Date(),
    public invoiceDueDate?: Date,
    public id?: number,
  ) {
    // Note: invoiceNumber is now generated by PaymentService.generateInvoiceNumber()
    // and should be set when converting to InvoiceEntity
    if (!this.invoiceDueDate) {
      this.invoiceDueDate = this.calculateDueDate(30);
    }
  }

  private calculateDueDate(daysToAdd: number): Date {
    const currentDate = new Date();
    const futureDate = new Date(currentDate);
    futureDate.setDate(currentDate.getDate() + daysToAdd);
    return futureDate;
  }

  private calculateTotalBill(): number {
    return this.bills.reduce((total, bill) => total + bill.fees.amount, 0);
  }
}
